In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('out.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57521 entries, 0 to 57520
Data columns (total 23 columns):
url                    57521 non-null object
itemName               57521 non-null object
currentPrice           53928 non-null object
oldPrice               26004 non-null object
description            40987 non-null object
averageRating          13770 non-null object
author                 55464 non-null object
editorialReviews       9529 non-null object
format                 15261 non-null object
category               57521 non-null object
release_date           18110 non-null object
isbn-13                30481 non-null object
publisher              39355 non-null object
publication_date       39391 non-null object
series                 13612 non-null object
pages                  28644 non-null object
sales_rank             26804 non-null object
product_dimensions     23788 non-null object
age_range              7109 non-null object
edition_description    6012 non-null object
file_size              15245 non-null object
upc                    18145 non-null object
original_release       63 non-null object
dtypes: object(23)
memory usage: 10.1+ MB

In [3]:
df.head()

,url,itemName,currentPrice,oldPrice,description,averageRating,author,editorialReviews,format,category,...,publication_date,series,pages,sales_rank,product_dimensions,age_range,edition_description,file_size,upc,original_release
0,https://www.barnesandnoble.com/w/nows-the-time...,Now's the Time,NaN,NaN,NaN,NaN,Sonny Rollins,NaN,NaN,Music,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0601704292724,NaN
1,https://www.barnesandnoble.com/w/on-becoming-c...,On Becoming Childwise: Parenting Your Child fr...,$15.11,$15.95,"As a child moves beyond the toddler years, new...",4.5,Gary Ezzo,NaN,NaN,Books,...,11/01/2001,NaN,261,"345,862",5.18(w) x 8.16(h) x 0.78(d),NaN,Reissue,NaN,NaN,NaN
2,https://www.barnesandnoble.com/w/fledgling-han...,The Fledgling Handbook 101,$15.29,$16.99,"Merry meet, fledgling. Welcome to a new life, ...",4.3,P. C. Cast,Cast and Cast pull out all the stops and take ...,NaN,Teen Books,...,10/26/2010,House of Night Series,157,"256,680",8.54(w) x 11.80(h) x 0.48(d),13 - 17 Years,NaN,NaN,NaN,NaN
3,https://www.barnesandnoble.com/w/best-silverto...,Best: Silvertone Years,$37.04,$38.99,NaN,NaN,Buddy Guy,NaN,NaN,Music,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4547366060225,NaN
4,https://www.barnesandnoble.com/w/quote-acrosti...,Quote Acrostic Favorites: Features 50 Rewardin...,$9.95,NaN,"If You Like Crossword Puzzles, You'll Love Acr...",NaN,Charles Preston,NaN,NaN,Books,...,08/01/2019,"Puzzle Books for Fun\n, #5",70,"781,068",8.50(w) x 11.02(h) x 0.14(d),NaN,NaN,NaN,NaN,NaN